# Generated by Django 4.2.4 on 2024-03-22 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_series', models.BooleanField(default=False)),
                ('series_end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_parent_person_relationship', to='crm.person')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_student_person_relationship', to='crm.person')),
            ],
        ),
        migrations.CreateModel(
            name='LessonAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_lesson_date', models.DateField(default=django.utils.timezone.now)),
                ('modified_start_time', models.DateTimeField()),
                ('modified_end_time', models.DateTimeField()),
                ('status', models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Canceled', 'Canceled')], max_length=64, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_lesson_relationship', to='crm.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessonSchedule_student_student_relationship', to='crm.student'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessonSchedule_teacher_user_relationship', to=settings.AUTH_USER_MODEL),
        ),
    ]
