# Generated by Django 4.2.4 on 2024-03-22 20:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonadjustment',
            name='original_lesson_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
