# Generated by Django 4.2.23 on 2025-08-29 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Uczeń', 'verbose_name_plural': 'Uczniowie'},
        ),
        migrations.RemoveField(
            model_name='attendancelist',
            name='lesson_date',
        ),
        migrations.AddField(
            model_name='attendancelist',
            name='event',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_list_event', to='crm.event'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Absense',
        ),
    ]
