# Generated by Django 4.2.23 on 2025-08-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendancelist',
            constraint=models.UniqueConstraint(fields=('event',), name='unique_event_attendance_list'),
        ),
    ]
