# Generated by Django 4.2.23 on 2025-08-31 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_attendancelist_unique_event_attendance_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupstudent',
            options={'verbose_name': 'Uczeń w grupie'},
        ),
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='invoice',
            new_name='invoice_item',
        ),
        migrations.AlterField(
            model_name='groupstudent',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_student_group_relationship', to='crm.group', verbose_name='Grupa'),
        ),
        migrations.AlterField(
            model_name='groupstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupStudent_student_relationship', to='crm.student', verbose_name='Uczeń'),
        ),
    ]
