# Generated by Django 4.2.4 on 2024-03-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_person_phone_alter_student_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonschedule',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
