# Generated by Django 4.2.4 on 2024-07-13 14:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_group_student_created_by_student_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentperson',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
