# Generated by Django 4.2.23 on 2025-08-31 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_groupstudent_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice_item',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crm.invoice', verbose_name='Faktura'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='amount',
            field=models.IntegerField(verbose_name='Kwota'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nazwa'),
        ),
    ]
