# Generated by Django 4.1.5 on 2024-04-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_student_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='slug',
        ),
    ]
