# Generated by Django 4.2.4 on 2024-03-09 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0004_alter_lessonschedule_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonschedule',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessonSchedule_student_student_relationship', to='crm.person'),
        ),
        migrations.AlterField(
            model_name='lessonschedule',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessonSchedule_teacher_user_relationship', to=settings.AUTH_USER_MODEL),
        ),
    ]
