# Generated by Django 4.2.4 on 2024-07-13 14:33

import apps.crm.models
from django.db import migrations

import apps.service_helper


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_studentperson_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=apps.service_helper.PrefixedUUIDField(max_length=39, primary_key=True, serialize=False, unique=True),
        ),
    ]
