# Generated by Django 4.2.4 on 2024-03-10 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_lessonschedule_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonschedule',
            old_name='starDate',
            new_name='startDate',
        ),
        migrations.RenameField(
            model_name='lessonschedule',
            old_name='time',
            new_name='startTime',
        ),
        migrations.AddField(
            model_name='lessonschedule',
            name='endTime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
