# Generated by Django 4.2.4 on 2024-03-10 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_rename_stardate_lessonschedule_startdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonschedule',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessonSchedule_student_student_relationship', to='crm.student'),
        ),
    ]
