# Generated by Django 4.2.4 on 2024-07-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_note_id_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='object_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
