# Generated by Django 4.1.5 on 2024-04-06 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_remove_student_parent_remove_student_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentperson',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_student_relationship', to='crm.student'),
        ),
    ]
