# Generated by Django 4.2.4 on 2024-07-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_notification_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='object_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='watchrecord',
            name='object_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
