# Generated by Django 4.1.5 on 2024-04-06 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_studentperson_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentperson',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_student_relationship', to='crm.student'),
        ),
    ]
