# Generated by Django 4.2.4 on 2024-07-13 15:38

import apps.crm.models
from django.db import migrations

import apps.service_helper


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_note_object_id_alter_watchrecord_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='id',
            field=apps.service_helper.PrefixedUUIDField(max_length=29, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='groupstudent',
            name='id',
            field=apps.service_helper.PrefixedUUIDField(max_length=29, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='id',
            field=apps.service_helper.PrefixedUUIDField(max_length=29, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lessonadjustment',
            name='id',
            field=apps.service_helper.PrefixedUUIDField(max_length=29, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=apps.service_helper.PrefixedUUIDField(max_length=29, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=apps.service_helper.PrefixedUUIDField(max_length=29, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=apps.service_helper.PrefixedUUIDField(max_length=29, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='studentperson',
            name='id',
            field=apps.service_helper.PrefixedUUIDField(max_length=29, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='watchrecord',
            name='id',
            field=apps.service_helper.PrefixedUUIDField(max_length=29, primary_key=True, serialize=False, unique=True),
        ),
    ]
