# Generated by Django 4.2.4 on 2024-03-15 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_student_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonDate', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('status', models.CharField(max_length=64)),
                ('comments', models.CharField(max_length=255)),
                ('lessonSchedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessonSchedule_lessonSchedule_relationship', to='crm.lessonschedule')),
            ],
        ),
    ]
