# Generated by Django 4.1.5 on 2024-04-06 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_studentperson_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentperson',
            old_name='parent',
            new_name='person',
        ),
    ]
