# Generated by Django 4.2.4 on 2024-07-25 20:55

import apps.crm.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

import apps.service_helper


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0009_alter_group_id_alter_groupstudent_id_alter_lesson_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='location',
            field=models.ForeignKey(default='0LC067255c0-b3bd-46f5-bb4c-fe76f2759ce1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='lessonSchedule_location_relationship', to='crm.location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonadjustment',
            name='location',
            field=models.ForeignKey(default='0LC067255c0-b3bd-46f5-bb4c-fe76f2759ce1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='lessonAdjustment_location_relationship', to='crm.location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonadjustment',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lessonAdjustment_teacher_user_relationship', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=apps.service_helper.PrefixedUUIDField(max_length=39, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='groupstudent',
            name='id',
            field=apps.service_helper.PrefixedUUIDField(max_length=39, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='id',
            field=apps.service_helper.PrefixedUUIDField(max_length=39, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lessonSchedule_teacher_user_relationship', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lessonadjustment',
            name='id',
            field=apps.service_helper.PrefixedUUIDField(max_length=39, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=apps.service_helper.PrefixedUUIDField(max_length=39, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=apps.service_helper.PrefixedUUIDField(max_length=39, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=apps.service_helper.PrefixedUUIDField(max_length=39, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=apps.service_helper.PrefixedUUIDField(max_length=39, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=apps.service_helper.PrefixedUUIDField(max_length=39, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='studentperson',
            name='id',
            field=apps.service_helper.PrefixedUUIDField(max_length=39, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='watchrecord',
            name='id',
            field=apps.service_helper.PrefixedUUIDField(max_length=39, primary_key=True, serialize=False, unique=True),
        ),
    ]
