# Generated by Django 4.2.4 on 2024-03-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_lessonadjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonadjustment',
            name='comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lessonadjustment',
            name='status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
