# Generated by Django 4.2.4 on 2024-07-29 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0010_lesson_location_lessonadjustment_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessonSchedule_location_relationship', to='crm.location'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessonSchedule_teacher_user_relationship', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lessonadjustment',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessonAdjustment_location_relationship', to='crm.location'),
        ),
        migrations.AlterField(
            model_name='lessonadjustment',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessonAdjustment_teacher_user_relationship', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Student_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Student_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
