# Generated by Django 4.2.4 on 2024-03-15 20:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_lessonadjustment_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonadjustment',
            name='originalLessonDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
