# Generated by Django 4.2.4 on 2024-03-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_lessonadjustment_originallessondate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonadjustment',
            name='status',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=64, null=True),
        ),
    ]
