# Generated by Django 4.2.4 on 2024-07-30 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_lesson_location_alter_lesson_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='groupstudent',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_student_group_relationship', to='crm.group'),
        ),
        migrations.AlterField(
            model_name='groupstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupStudent_student_relationship', to='crm.student'),
        ),
        migrations.AlterField(
            model_name='studentperson',
            name='relationship_type',
            field=models.CharField(choices=[('Matka', 'Matka'), ('Ojciec', 'Ojciec'), ('Babcia', 'Babcia'), ('Dziadek', 'Dziadek'), ('Inna', 'Inna')], max_length=100),
        ),
    ]
