# Generated by Django 4.2.4 on 2024-03-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_lessonadjustment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonadjustment',
            name='status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Canceled', 'Canceled')], max_length=64, null=True),
        ),
    ]
