# Generated by Django 4.2.4 on 2024-05-19 13:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0012_wachrecord'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WachRecord',
            new_name='WatchRecord',
        ),
    ]
