# Generated by Django 4.2.4 on 2024-09-23 17:56

import apps.service_helper
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_group_created_by_group_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceList',
            fields=[
                ('id', apps.service_helper.PrefixedUUIDField(max_length=39, primary_key=True, serialize=False, unique=True)),
                ('lesson_date', models.DateTimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_group_relationship', to='crm.group')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessonSchedule_lesson_group_relationship', to='crm.group'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessonSchedule_student_student_relationship', to='crm.student'),
        ),
        migrations.AlterUniqueTogether(
            name='groupstudent',
            unique_together={('group', 'student')},
        ),
        migrations.CreateModel(
            name='AttendanceListStudent',
            fields=[
                ('id', apps.service_helper.PrefixedUUIDField(max_length=39, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(blank=True, choices=[('Obecnosc', 'Obecność'), ('Nieobecnosc', 'Nieobecność'), ('Spoznienie', 'Spoznienie')], max_length=64, null=True)),
                ('attendance_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.attendancelist')),
            ],
        ),
    ]
