# Generated by Django 4.2.4 on 2024-10-04 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_attendancelist_lesson_group_alter_lesson_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceliststudent',
            name='attendance_list',
            field=models.ForeignKey(default='Obecnosc', on_delete=django.db.models.deletion.CASCADE, to='crm.attendancelist'),
        ),
    ]
