# Generated by Django 4.2.4 on 2024-10-04 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_alter_attendanceliststudent_attendance_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceliststudent',
            name='student',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='crm.student'),
            preserve_default=False,
        ),
    ]
