# Generated by Django 4.2.4 on 2024-10-04 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_attendanceliststudent_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceliststudent',
            name='attendance_list',
            field=models.ForeignKey(default='Obecnosc', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_list_student_group_relationship', to='crm.attendancelist'),
        ),
    ]
