# Generated by Django 4.2.4 on 2024-10-05 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_alter_attendanceliststudent_attendance_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceliststudent',
            name='attendance_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_list_student_group_relationship', to='crm.attendancelist'),
        ),
        migrations.AlterField(
            model_name='attendanceliststudent',
            name='status',
            field=models.CharField(blank=True, choices=[('Obecnosc', 'Obecność'), ('Nieobecnosc', 'Nieobecność'), ('Spoznienie', 'Spoznienie')], default='Obecnosc', max_length=64, null=True),
        ),
    ]
