# Generated by Django 4.2.4 on 2024-10-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_alter_attendanceliststudent_attendance_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceliststudent',
            name='status',
        ),
        migrations.AddField(
            model_name='attendanceliststudent',
            name='attendance_status',
            field=models.CharField(blank=True, choices=[('Obecnosc', 'Obecność'), ('Nieobecnosc', 'Nieobecność'), ('Spoznienie', 'Spóźnienie')], default='Obecnosc', max_length=64, null=True),
        ),
    ]
