# Generated by Django 4.2.4 on 2024-10-08 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_invoice_invoiceitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='month',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='year',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
