# Generated by Django 4.2.4 on 2024-10-14 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0021_remove_invoice_month_remove_invoice_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attenndancelist_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancelist',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancelist',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attenndancelist_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancelist',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
