# Generated by Django 4.1.5 on 2024-11-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_attendancelist_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Grupa', 'verbose_name_plural': 'Grupy'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Lokalizacja', 'verbose_name_plural': 'Lokalizacje'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Kontakt', 'verbose_name_plural': 'Kontakty'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Studenci'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='object_id',
            field=models.CharField(blank=True, max_length=39, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='object_id',
            field=models.CharField(blank=True, max_length=39, null=True),
        ),
        migrations.AlterField(
            model_name='watchrecord',
            name='object_id',
            field=models.CharField(blank=True, max_length=39, null=True),
        ),
    ]
