# Generated by Django 4.2.4 on 2024-11-24 20:59

import apps.service_helper
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0022_attendancelist_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonDefinition',
            fields=[
                ('id', apps.service_helper.PrefixedUUIDField(max_length=39, primary_key=True, serialize=False, unique=True)),
                ('series_start_date', models.DateField()),
                ('series_end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_series', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Grupa', 'verbose_name_plural': 'Grupy'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Lokalizacja', 'verbose_name_plural': 'Lokalizacje'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Kontakt', 'verbose_name_plural': 'Kontakty'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Studenci'},
        ),
        migrations.AlterField(
            model_name='note',
            name='object_id',
            field=models.CharField(blank=True, max_length=39, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='object_id',
            field=models.CharField(blank=True, max_length=39, null=True),
        ),
        migrations.AlterField(
            model_name='watchrecord',
            name='object_id',
            field=models.CharField(blank=True, max_length=39, null=True),
        ),
        migrations.CreateModel(
            name='LessonEvent',
            fields=[
                ('id', apps.service_helper.PrefixedUUIDField(max_length=39, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('Zaplanowana', 'Zaplanowana'), ('Nieobecnosc', 'Nieobecność'), ('Odwolana - nauczyciel', 'Odwołana - nauczyciel'), ('Odwolana - 24h przed', 'Odwołana - 24h przed')], max_length=100)),
                ('lesson_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('lesson_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.lessondefinition')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.location')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lessondefinition',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.group'),
        ),
        migrations.AddField(
            model_name='lessondefinition',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.location'),
        ),
        migrations.AddField(
            model_name='lessondefinition',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.student'),
        ),
        migrations.AddField(
            model_name='lessondefinition',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
