# Generated by Django 4.2.4 on 2025-01-29 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_lessondefinition_alter_group_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessondefinition',
            old_name='series_start_date',
            new_name='lesson_date',
        ),
        migrations.AlterField(
            model_name='lessondefinition',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.group'),
        ),
        migrations.AlterField(
            model_name='lessondefinition',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.student'),
        ),
        migrations.AddConstraint(
            model_name='lessondefinition',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('group__isnull', False), ('student__isnull', True)), models.Q(('group__isnull', True), ('student__isnull', False)), _connector='OR'), name='crm_lessondefinition_student_or_group'),
        ),
    ]
