# Generated by Django 4.2.4 on 2025-01-29 22:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_rename_series_start_date_lessondefinition_lesson_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonevent',
            name='end_time',
        ),
        migrations.AddField(
            model_name='lessonevent',
            name='duration',
            field=models.IntegerField(choices=[(30, '30 min'), (60, '60 min')], default=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonevent',
            name='original_lesson_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
