# Generated by Django 4.2.4 on 2025-02-02 17:30

import apps.service_helper
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0025_remove_lessonevent_end_time_lessonevent_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_type', models.CharField(choices=[('lesson', 'Lekcja'), ('standard', 'Standardowe Wydarzenie')], default='standard', max_length=32)),
                ('id', apps.service_helper.PrefixedUUIDField(max_length=39, primary_key=True, serialize=False, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('event_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('zaplanowana', 'Zaplanowana'), ('nieobecnosc', 'Nieobecność'), ('odwolana_nauczyciel', 'Odwołana - nauczyciel'), ('odwolana_24h_przed', 'Odwołana - 24h przed')], max_length=100)),
                ('original_lesson_date', models.DateField()),
                ('duration', models.IntegerField(choices=[(30, '30 min'), (60, '60 min')])),
            ],
        ),
        migrations.RemoveField(
            model_name='lessondefinition',
            name='end_time',
        ),
        migrations.AddField(
            model_name='lessondefinition',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lessondefinition',
            name='duration',
            field=models.IntegerField(choices=[(30, '30 min'), (60, '60 min')], default=60),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LessonEvent',
        ),
        migrations.AddField(
            model_name='event',
            name='lesson_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.lessondefinition'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.location'),
        ),
        migrations.AddField(
            model_name='event',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
