# Generated by Django 4.2.4 on 2025-02-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_event_remove_lessondefinition_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessondefinition',
            name='series_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
