# Generated by Django 4.2.4 on 2025-02-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_alter_lessondefinition_series_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
