# Generated by Django 4.2.4 on 2025-02-02 22:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_alter_event_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='original_lesson_date',
        ),
        migrations.AddField(
            model_name='event',
            name='original_lesson_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
