# Generated by Django 4.2.4 on 2025-06-20 17:44

import apps.service_helper
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('crm', '0029_remove_event_original_lesson_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.IntegerField(choices=[(30, '30 min'), (45, '45 min'), (60, '60 min')]),
        ),
        migrations.AlterField(
            model_name='lessondefinition',
            name='duration',
            field=models.IntegerField(choices=[(30, '30 min'), (45, '45 min'), (60, '60 min')]),
        ),
        migrations.CreateModel(
            name='FieldHistory',
            fields=[
                ('id', apps.service_helper.PrefixedUUIDField(max_length=39, primary_key=True, serialize=False, unique=True)),
                ('object_id', models.CharField(max_length=39)),
                ('field_name', models.CharField(max_length=255)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
