# Generated by Django 4.2.4 on 2024-05-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
