# Generated by Django 4.2.4 on 2024-07-29 11:57

import apps.authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=apps.authentication.models.PrefixedUUIDField(max_length=39, primary_key=True, serialize=False, unique=True),
        ),
    ]
